name: dependency_module
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_inappwebview: ^5.3.2
  shared_preferences: ^2.0.13
  get: ^4.6.1
  url_launcher:
  flutter:
    sdk: flutter
  flutter_mobx:
  flutter_modular: ^4.5.0
  mobx: ^2.0.6+1
  dio: ^4.0.4
  sqflite: ^2.0.0+4
  fluttermoji: ^0.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
