name: film_module
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  design_system_module:
    path: ../design_system_module
  dependency_module:
    path: ../dependency_module
  database_module:
    path: ../database_module
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2

flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - 'assets/imgs/carregandogif.gif'
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding a